### PR TITLE
updated to correct classname.  Fixes phpunit tests

### PR DESCRIPTION
**Pull request by ehsan42**
https://github.com/moodle/moodle/commit/4003e31983e7ddc3e4c75aba3b1e0d6fb7d8a28b#diff-86bfdc09667302d89acc1baed21dea01066551e88c2f12d37b2fb23e80ef7daf

### CODE REVIEW

**Comment by jpahullo** [comment]
I can see that from Moodle 3.11 onwards, we need this change. It also means we need to provide a new version that only supports M3.11 onwards. Let us check this and build the corresponding tagging and plugin version.

**Comment by jpahullo** [comment]
Thanks a lot @ehsan42 !!!

**Comment by hdagheda** [comment]
Hi @jpahullo, any updates on 3.11 supported version?

**Comment by jpahullo** [comment]
Base test class was solved on the last release from today.

**Pull request closed without merging**
