### PR TITLE
Add CSV export and merged by user to logs.

### PR DESCRIPTION
**Pull request by marxjohnson**
This change adds a link to the Merged user logs page to download the logs shown in the table as a CSV file.
It also adds a new field to the logs, which records the user who performed the merge. This is displayed on the page, and included in the CSV export.

### CODE REVIEW

**Comment by jpahullo** [comment]
I've just reviewed the code and it seems good for me. Let de CI pass and we will be able to accept this PR.

Thanks a lot for your contribution @marxjohnson!

**Comment by jpahullo** [comment]
Hi @marxjohnson, we need a bit of working from our side to provide versioning for up to Moodle 3.11 (excluded) and Moodle 3.11 onwards, to keep phpunit tests passing. We'll merge this PR as soon as possible. Thanks for your work!

**Comment by marxjohnson** [comment]
We found an issue in testing with errors being thrown for legacy records with no "mergedbyuserid" recorded, so this additional commit resolves that.

**Comment by jpahullo** [comment]
I've been testing this.

I can see that when using the climerger.php, there is no user set, so that it is stated as not defined: `Not recorded`. It's ok. 

And the utility to export is shown above the page of logs, as of the form: [Export logs as CSV](http://localhost/admin/tool/mergeusers/view.php?export=1). 

It seems nice to me.

Integrating as `2023040401` release tag.

**Comment by jpahullo** [comment]
Thanks. Your work is available under https://moodle.org/plugins/tool_mergeusers/2023040401/28884

**Comment by jpahullo** [comment]
Hi,

@marxjohnson, @sarahjcotton 

This PR consisting on enabling downloading merging logs as CSV is available under the plugin version: https://moodle.org/plugins/tool_mergeusers/2023040401/28884

Thanks a lot for your contribution,

Jordi

**Pull request merged**
